### ISSUE TITLE
pip install fails because of missing README.md

### ISSUE THREAD

**Issue by adamghill** [austinmcconnell/mortgage#6]
I get this error when attempting to install with `pip`:
```
File "/private/var/folders/28/zgtt7wsn41z8rlnqy8cxj4xw0000gn/T/pip-build-O
B10UC/mortgage/setup.py", line 3, in <module>
        with open('README.md') as readme_file:
    IOError: [Errno 2] No such file or directory: 'README.md'
```
When I downloaded the gzip file from https://pypi.python.org/pypi/mortgage/1.0.0, it does appear to be missing the README.md file. If I git clone and `pip install -e`, the library gets installed correctly.

**Comment by austinmcconnell** [comment]
Thanks again for pointing this out. I was able to duplicate the error message you got.

I pushed a new version (1.0.1) up to PyPI and tested it on my machine. It installed successfully for me. Try the new version and let me know if it works for you as well.

**Comment by adamghill** [comment]
Yep, I did a `pip install mortgage` and it installed 1.0.1 correctly. Thanks for the quick merge!
